---
name: Molecule
"on":
  push: {}
  pull_request: {}
jobs:
  molecule:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python_version: ["3.12"]
        experimental: [false]
        molecule_image:
          - ghcr.io/agoloncser/docker-molecule-fedora:39
          - ghcr.io/agoloncser/docker-molecule-ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Molecule test
        run: pipenv run molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.molecule_image }}
